---
#- name : (Ubuntu) add docker apt key
#  apt_key:
#    url: "{{ apt_docker_key }}"
#    id: "{{ apt_docker_key_id }}"
#    state: present

- name: remove sources.list
  file:
    path: /etc/apt/sources.list
    state: absent

- name: APT System Repo
  copy:
    dest: /etc/apt/sources.list.d/apt_archive_main_repo.list
    content: "{{ apt_archive_main_repo }}"
    owner: root
    group: root
    mode: 0644

- name: APT System Repo
  copy:
    dest: /etc/apt/sources.list.d/apt_archive_updates_repo.list
    content: "{{ apt_archive_updates_repo }}"
    owner: root
    group: root
    mode: 0644

- name: APT System Repo
  copy:
    dest: /etc/apt/sources.list.d/apt_archive_universe_repo.list
    content: "{{ apt_archive_universe_repo }}"
    owner: root
    group: root
    mode: 0644

- name: APT System Repo
  copy:
    dest: /etc/apt/sources.list.d/apt_archive_universe_updates_repo.list
    content: "{{ apt_archive_universe_updates_repo }}"
    owner: root
    group: root
    mode: 0644

- name: APT System Repo
  copy:
    dest: /etc/apt/sources.list.d/apt_archive_multiverse_repo.list
    content: "{{ apt_archive_multiverse_repo }}"
    owner: root
    group: root
    mode: 0644

- name: APT System Repo
  copy:
    dest: /etc/apt/sources.list.d/apt_archive_multiverse_updates_repo.list
    content: "{{ apt_archive_multiverse_updates_repo }}"
    owner: root
    group: root
    mode: 0644

- name: APT System Repo
  copy:
    dest: /etc/apt/sources.list.d/apt_security_main_repo.list
    content: "{{ apt_security_main_repo }}"
    owner: root
    group: root
    mode: 0644

- name: APT System Repo
  copy:
    dest: /etc/apt/sources.list.d/apt_security_universe_repo.list
    content: "{{ apt_security_universe_repo }}"
    owner: root
    group: root
    mode: 0644

- name: APT System Repo
  copy:
    dest: /etc/apt/sources.list.d/apt_security_multiverse_repo.list
    content: "{{ apt_security_multiverse_repo }}"
    owner: root
    group: root
    mode: 0644

- name: Install Deb Package management
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - python-apt
